class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start7'
        self.MirrorCommand = 'dl7'
        self.UnzipMirrorCommand = 'unzip7'
        self.TarMirrorCommand = 'tar7'
        self.ZipMirrorCommand = 'zip7'
        self.CancelMirror = 'batal7'
        self.CancelAllCommand = 'batalin7'
        self.ListCommand = 'cari7'
        self.StatusCommand = 'status7'
        self.AuthorizedUsersCommand = 'users7'
        self.AuthorizeCommand = 'auth7'
        self.UnAuthorizeCommand = 'unauth7'
        self.AddSudoCommand = 'addsudo7'
        self.RmSudoCommand = 'rmsudo7'
        self.PingCommand = 'ping7'
        self.RestartCommand = 'restart7'
        self.StatsCommand = 'stat7'
        self.HelpCommand = 'bantuan7'
        self.LogCommand = 'log7'
        self.SpeedCommand = 'speedtest7'
        self.CloneCommand = 'salin7'
        self.CountCommand = 'hitung7'
        self.WatchCommand = 'watch7'
        self.TarWatchCommand = 'tarwatch7'
        self.DeleteCommand = 'del7'
        self.ConfigMenuCommand = 'config7'
        self.ShellCommand = 'shell7'
        self.UpdateCommand = 'update7'
        self.ExecHelpCommand = 'exechelp7'
        self.TsHelpCommand = 'tshelp7'

BotCommands = _BotCommands()
